"""create tasks table

Revision ID: 4a8624b6b3a5
Revises: d1a092a64f0d
Create Date: 2024-12-15 14:41:17.313653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a8624b6b3a5'
down_revision: Union[str, None] = 'd1a092a64f0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prompts', 'template_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prompts', 'template_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
